In [164]:
%load_ext autoreload
%autoreload 2

import torch
from utility.attentionAutoEncoder import AttentionAutoEncoder, concate_data, AttentionDataset
from torch.utils.data import DataLoader

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [165]:
model = AttentionAutoEncoder(3, 5, 2)

In [166]:
input_data = torch.randn(3, 5)
input_data

tensor([[-0.6871,  1.0714,  1.2645, -0.0397,  0.0194],
        [-0.2122,  0.2750, -0.3443,  0.9146,  0.1828],
        [ 0.0606,  1.0093,  0.7058, -0.5626, -0.8769]])

In [167]:
model(input_data)

tensor([[ 0.0047, -0.0214, -0.0268,  0.0290,  0.0233]], grad_fn=<MmBackward0>)

In [168]:
import pandas as pd
from utility.data_processing import set_time_data

In [169]:
dfs = dict()
for ticker in ['btc', 'eth', 'doge', 'xrp', 'ada']:
  currency_metrics = pd.read_csv(f'../data/{ticker}_metrics_5_years.csv')
  set_currency_metrics = set_time_data(currency_metrics)
  dfs[ticker] = set_currency_metrics

In [170]:
res = concate_data(dfs)

In [171]:
X_t = res[:, :, 0]

In [172]:
model(X_t)

tensor([[ 0.0864, -0.3962, -0.4955,  0.5365,  0.4308]], grad_fn=<MmBackward0>)

In [173]:
X_t.shape[-1]

5

In [174]:
dataset = AttentionDataset(res)

In [175]:
# Create DataLoader
dataloader = DataLoader(dataset, batch_size=50, shuffle=True, num_workers=0)

# Iterate through DataLoader
for batch in dataloader:
    print(batch.shape)  # Output: torch.Size([10, 5])
    break  # To print only one batch

torch.Size([50, 3, 5])


In [176]:
model(batch)

RuntimeError: The size of tensor a (50) must match the size of tensor b (3) at non-singleton dimension 0